# Generated by Django 5.1.7 on 2025-05-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_dash_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('phone_number', models.CharField(max_length=15)),
                ('id_proof', models.ImageField(upload_to='id_proofs/')),
                ('comment', models.TextField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
            ],
        ),
    ]
