# Generated by Django 5.1.7 on 2025-05-02 09:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biz_dash_app', '0002_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='staff',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
